### PR TITLE
Fix encoding of repeated string & bytes fields in proto3 messages

### PR DESCRIPTION
**Pull request by mloughran**
From https://developers.google.com/protocol-buffers/docs/encoding#packed

> In proto3, repeated fields of scalar numeric types are packed by default. 

The current implementation incorrectly sends string & byte fields packed. This doesn't work.

### Example

```protobuf
# example.proto
syntax = "proto3";
message RepeatedString {
  repeated string foo = 1;
}
```

	# example.data
	foo: "foo"
	foo: "bar"
	foo: "baz"

```crystal
# encode.cr
require "./example.pb"
RepeatedString.new(foo: ["foo", "bar", "baz"]).to_protobuf(STDOUT)
```

```crystal
# decode.cr
require "./example.pb"
p RepeatedString.from_protobuf(STDIN)
```

### Encoding

This produces incorrect output:

	$ protoc --crystal_out=. example.proto

	$ crystal run encode.cr | protoc --decode=RepeatedString example.proto
	foo: "\003foo\003bar\003baz"

and does not agree with the output of `protoc`:

	$ cat example.data | protoc --encode=RepeatedString example.proto

With this PR this is fixed:

	$ crystal run encode.cr | protoc --decode=RepeatedString example.proto
	foo: "foo"
	foo: "bar"
	foo: "baz"

### Decoding

Decoding is affected by the same issue, and causes an exception:

Before:

	$ cat example.data | protoc --encode=RepeatedString example.proto | crystal run decode.cr
	Unhandled exception: End of file reached (IO::EOFError)
	...

With PR:

	$ cat example.data | protoc --encode=RepeatedString example.proto | crystal run decode.cr
	RepeatedString(@foo=["foo", "bar", "baz"])

### Difference on the wire

Before:

	% crystal run encode.cr | hexdump
	0000000 0a 0c 03 66 6f 6f 03 62 61 72 03 62 61 7a
	000000e

With PR:

	% crystal run encode.cr | hexdump
	0000000 0a 03 66 6f 6f 0a 03 62 61 72 0a 03 62 61 7a
	000000f

The second is correct (3 groups of `0a 03 66 6f 6f`, rather than packed format).

### Specs

I haven't written any, and existing specs still pass. Let me know if you'd like me to try adding. My thoughts are:

* Add repeated string example to `test3.proto`
* Adjust `test.data` and `test.data.encoded` accordingly

### CODE REVIEW

**Comment by jgaskins** [comment]
Just confirmed with the Ruby Protobuf library maintained by Google with your example message, as well. Surprising that my NATS Streaming and OpenTelemetry libraries built with this shard didn't exhibit this problem. I would've thought repeated strings would be more common.

> existing specs still pass. Let me know if you'd like me to try adding

This would be great. We have [a message-encoding spec](https://github.com/jeromegn/protobuf.cr/blob/master/spec/protobuf/encexamples_spec.cr), which seems like a good place to put a test since you've already examined the generated bytes.

Unfortunately the test suite doesn't recompile `.proto` files yet, so any new properties added to existing `.proto` files will require regenerating them. I'd love to get the test suite to where it can start the test run with no messages compiled and exercise the entire process including codegen but finding the motivation for that lately has been difficult.

**Comment by mloughran** [comment]
Thanks @jgaskins. I've addressed the test data issue first since it should hopefully make adding specs for this easier, and will rebase this PR on top – see #46.

**Comment by jgaskins** [comment]
@mloughran #46 is merged and CI is updated to use it. Ready for rebase.

**Comment by mloughran** [comment]
@jgaskins thanks for merging and the CI additions 😄  Adding proto3 specs was a little involved so I've opened PR #47 for that and will rebase this on top.

**Comment by jgaskins** [comment]
Looks great! Thank you for all your effort!

**Comment by jgaskins** [comment]
… and the yak shave

**Pull request merged**
